# Generated by Django 4.0.6 on 2022-08-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_data_nascimento_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='core', verbose_name='IMG'),
        ),
    ]
