# Generated by Django 4.0.6 on 2022-09-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=25, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('m', 'masculino'), ('f', 'feminino'), ('o', 'outro')], max_length=1, null=True)),
            ],
        ),
    ]
