# Generated by Django 4.0.6 on 2022-09-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
